platform :ios, '10.3'

target 'MovieExplorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieExplorer
  pod 'Alamofire', '~> 4.4'

  target 'MovieExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieExplorerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end