platform :ios, '10.3'

target 'MovieExplorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieExplorer
  pod 'RxAlamofire'
  pod 'ObjectMapper', '~> 2.2'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Swinject', '~> 2.0.0'

  target 'MovieExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieExplorerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
